### ISSUE TITLE
Countries and Their Acronym Aliases Showing Up As Separate Nodes

### ISSUE THREAD

**Issue by NirantK** [NirantK/coronaIndia#14]
From https://github.com/someshkar/covid19india-cluster/issues/148

**Comment by NirantK** [comment]
@rohanrmallya would you like to work on this? It seems like I've not been able to devote enough time to this right now.

**Comment by rohanrmallya** [comment]
I'm on it!
Thanks.

**Comment by NirantK** [comment]
Thanks for looking into this! Assigned the issue to you

**Comment by rohanrmallya** [comment]
> Thanks for looking into this! Assigned the issue to you

Hi, have raised a PR. #23 
Forgot to update here.
