### ISSUE TITLE
Data error in travel history sheet https://api.steinhq.com/v1/storages/5e737e60b88d3d04ae0815b8/Sheet1

### ISSUE THREAD

**Issue by KSaiVinod** [NirantK/coronaIndia#17]
Error in travel history datasheet getting an error while accessing saying  "error": "Unexpected token f in JSON at position 0"

**Comment by NirantK** [comment]
The experimental endpoint is this: https://api.steinhq.com/v1/storages/5e737e60b88d3d04ae0815b8/PatientTravelHistory

The stable endpoint is https://api.covid19india.org/travel_history.json

Please use the stable endpoint.
